#!/bin/bash
################################################################################ 
# 
# goquery
# 
# Wrapper script used for querying the go database and nicing the process
# appropriately 
# 
# Written by Lennart Elsen 
#        and Fabian  Kohn, August 2014 
# Copyright (c) 2014 Open Systems AG, Switzerland 
# All Rights Reserved.
#
################################################################################
# This code has been developed by Open Systems AG
#
# goProbe is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# goProbe is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with goProbe; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

#-------------------------------------------------------------------------------
# Global Constants
#-------------------------------------------------------------------------------
PKG=goProbe

GQNAME="goQuery"
GQNICEVAL=10

# read in the arguments as they are supposed to be passed to goQuery
args=""
for i in "$@"; do
    if [[ "$i" =~ "=" ]]; then
	tmpvar=$(echo $i | sed 's# ##g')
        args=$args"$tmpvar "
    else
	args=$args"$i "
    fi
done

# run goQuery with specified nice value
export LD_LIBRARY_PATH=/usr/local/$PKG/lib
nice -n $GQNICEVAL /usr/local/$PKG/bin/${GQNAME} ${args}
